In [70]:
import pandas as pd

In [71]:
path = r'C:\Users\Vegh\Documents\Estudo\estudos-engenharia-dados\pandas\hotels-dataset\hotel_data.csv'

df_hotels = pd.read_csv(path, sep=',')

In [72]:
display(df_hotels)

,name,Zip code,Number of reviewers,Overall score,Cleanliness,Comfort,Facilities,Staff,Value for money,Free WiFi,...,Terrace,Swimming Pool,very good Fitness Center,Restaurant,Private Beach Area,exceptional Fitness Center,24-Hour Front Desk,WiFi,BBQ Facilities,Dist
0,Sheraton Gateway Los Angeles,90045,"5,663",8.1,8.5,8.4,8.0,7.8,7.4,7.2,...,0,1,0,0,0,0,0,0,0,(11.2 miles from center)
1,The Jeremy Hotel West Hollywood,90069,563,8.9,9.3,9.0,8.7,8.9,8.2,9.5,...,0,1,0,0,0,0,0,0,0,(8.1 miles from center)
2,Hollywood Proper Residences,90028,0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,...,0,1,0,0,0,0,0,0,0,(5.6 miles from center)
3,Hampton Inn & Suites Santa Monica,90401,867,8.3,8.8,8.6,8.2,8.2,7.2,8.4,...,0,1,1,0,0,0,0,0,0,(14.3 miles from center)
4,Spacious Apartment in Westwood UCLA *27,90024,0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,...,0,1,0,0,0,0,0,0,0,(11.8 miles from center)
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1000,Franklin Plaza,90028,0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,...,0,0,0,0,0,0,0,0,0,(5 miles from center)
1001,Sleek Midcity Studio Cottage,90019,0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,...,0,0,0,0,0,0,0,0,1,(5 miles from center)
1002,Beverly Hills Modern Guesthouse,90211,0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,...,1,0,0,0,0,0,0,0,0,(7.5 miles from center)
1003,Vintage Modern Lofts of Downtown LA-3,90014,0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,...,0,0,0,0,0,0,0,0,0,(0.9 miles from center)
1004,Hollywood studio | Free parking | Walkable | Q...,90046,0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,...,0,1,0,0,0,0,0,0,0,(6.8 miles from center)

In [73]:
df_hotels.describe()

,Zip code,Overall score,Cleanliness,Comfort,Facilities,Staff,Value for money,Free WiFi,Location,good Fitness Center,...,Non-smoking Rooms,Terrace,Swimming Pool,very good Fitness Center,Restaurant,Private Beach Area,exceptional Fitness Center,24-Hour Front Desk,WiFi,BBQ Facilities
count,1005.000000,1005.000000,582.000000,582.000000,582.000000,582.000000,582.000000,582.000000,582.000000,1005.000000,...,1005.000000,1005.000000,1005.000000,1005.000000,1005.000000,1005.000000,1005.000000,1005.000000,1005.000000,1005.000000
mean,89855.413930,4.853831,8.516495,8.478007,8.301890,8.433333,7.834536,8.546392,9.057732,0.008955,...,0.815920,0.084577,0.570149,0.004975,0.024876,0.000995,0.000995,0.033831,0.034826,0.059701
std,4982.457298,4.166306,0.710024,0.697942,0.758779,0.745443,0.745331,1.196141,18.629477,0.094254,...,0.387742,0.278390,0.495301,0.070394,0.155824,0.031544,0.031544,0.180884,0.183430,0.237051
min,-3310.000000,0.000000,6.000000,5.400000,5.600000,4.700000,4.300000,2.500000,1.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,90017.000000,0.000000,8.100000,8.100000,7.800000,8.000000,7.300000,8.000000,7.800000,0.000000,...,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,90028.000000,7.800000,8.600000,8.500000,8.300000,8.500000,7.800000,8.700000,8.600000,0.000000,...,1.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
75%,90069.000000,8.500000,9.000000,8.900000,8.800000,8.900000,8.300000,9.400000,9.100000,0.000000,...,1.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
max,91608.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,356.000000,1.000000,...,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000

In [74]:
columns = ['name', 'Zip_code', 'Number_of_reviewers', 'Overall_score',
       'Cleanliness', 'Comfort', 'Facilities', 'Staff', 'Value_for_money',
       'Free_WiFi', 'Location', 'good_Fitness_Center', 'Daily_Housekeeping',
       'Heating', 'Free_Parking', 'Airport_Shuttle_(free)', 'Private_Parking',
       'Spa', 'On-site_Parking', 'Fitness_Center', 'Room_Service',
       'Family_Rooms', 'Parking', 'Airport_Shuttle', 'Air_Conditioning',
       'Free_WiFi.1', 'Laundry', 'Water_Park', 'Pet_Friendly', 'Outdoor_Pool',
       'Indoor_Pool', 'Elevator', 'Garden', 'Facilities_for_Disabled_Guests',
       'Bar', 'Beach_nearby', 'wonderful_Fitness_Center', 'Beachfront',
       'Non-smoking_Rooms', 'Terrace', 'Swimming_Pool',
       'very_good_Fitness_Center', 'Restaurant', 'Private_Beach_Area',
       'exceptional_Fitness_Center', '24-Hour_Front_Desk', 'WiFi',
       'BBQ_Facilities', 'Dist']

cols_new = [col.lower() for col in columns]

In [75]:
df_hotels.columns = cols_new
df_hotels.sample()

,name,zip_code,number_of_reviewers,overall_score,cleanliness,comfort,facilities,staff,value_for_money,free_wifi,...,terrace,swimming_pool,very_good_fitness_center,restaurant,private_beach_area,exceptional_fitness_center,24-hour_front_desk,wifi,bbq_facilities,dist
663,NEW! LUXURY SUITE with Parking!,90017,6,9.0,8.8,8.8,9.2,9.2,8.8,9.2,...,0,1,0,0,0,0,0,0,0,(1.1 miles from center)

In [76]:
df_hotels.sort_values(by=['overall_score'], ascending=False, inplace=True)
df_hotels.head(10)

,name,zip_code,number_of_reviewers,overall_score,cleanliness,comfort,facilities,staff,value_for_money,free_wifi,...,terrace,swimming_pool,very_good_fitness_center,restaurant,private_beach_area,exceptional_fitness_center,24-hour_front_desk,wifi,bbq_facilities,dist
783,Double Suite in Santa Monica,90403,7,10.0,10.0,10.0,10.0,10.0,9.7,10.0,...,1,0,0,0,0,0,0,0,0,(13.7 miles from center)
363,Selby Ave Guest House,90064,75,10.0,10.0,9.9,10.0,9.9,9.9,10.0,...,1,1,0,0,0,0,0,0,0,(9.9 miles from center)
649,"Sunset Strip 1-Bedroom with Balcony, Pool and ...",90046,6,9.9,10.0,10.0,10.0,9.6,9.6,10.0,...,0,1,0,0,0,0,0,0,0,(7.5 miles from center)
71,LA Deluxe Suite at The Grove Mall,90036,8,9.8,9.7,9.7,9.4,10.0,10.0,10.0,...,0,1,0,0,0,0,0,0,0,(6.2 miles from center)
703,Desert Heaven - Guest House,91604,173,9.8,9.9,9.9,9.8,9.9,9.7,9.9,...,0,0,0,0,0,0,0,0,0,(9.9 miles from center)
131,W. HOLLYWOOD CHARMING 2BR/2BT SUITE / Free Par...,90036,6,9.8,10.0,9.6,10.0,10.0,9.6,9.6,...,0,1,0,0,0,0,0,0,0,(5.6 miles from center)
743,Tiverton Apartment Lofts,90024,5,9.8,10.0,10.0,10.0,9.5,9.0,10.0,...,0,0,0,0,0,0,0,0,1,(11.2 miles from center)
153,Sunset Boulevard Luxury Private Home Escape,90028,5,9.7,9.5,10.0,10.0,9.5,9.5,9.5,...,0,0,0,0,0,0,0,0,0,(6.2 miles from center)
892,WeHo Bungalow with Private Garden,90046,16,9.7,9.7,10.0,10.0,10.0,9.1,10.0,...,0,0,0,0,0,0,0,0,0,(6.2 miles from center)
119,"Marina Del Rey/Venice 2 Bed, 2 Bath. Pool, Gym",90292,6,9.7,9.6,9.6,10.0,9.6,9.6,9.6,...,0,1,0,0,0,0,0,0,0,(12.4 miles from center)

In [78]:
udf = lambda x : str(x).replace('1', 'YES') if x == 1 else str(x).replace('0', 'NO')
df_pools['has_pool'] = df_pools.swimming_pool.apply(udf)

In [79]:
df_hotels.loc[(df_hotels['swimming_pool'] != 1 )].head(5)

,name,zip_code,number_of_reviewers,overall_score,cleanliness,comfort,facilities,staff,value_for_money,free_wifi,...,terrace,swimming_pool,very_good_fitness_center,restaurant,private_beach_area,exceptional_fitness_center,24-hour_front_desk,wifi,bbq_facilities,dist
783,Double Suite in Santa Monica,90403,7,10.0,10.0,10.0,10.0,10.0,9.7,10.0,...,1,0,0,0,0,0,0,0,0,(13.7 miles from center)
703,Desert Heaven - Guest House,91604,173,9.8,9.9,9.9,9.8,9.9,9.7,9.9,...,0,0,0,0,0,0,0,0,0,(9.9 miles from center)
743,Tiverton Apartment Lofts,90024,5,9.8,10.0,10.0,10.0,9.5,9.0,10.0,...,0,0,0,0,0,0,0,0,1,(11.2 miles from center)
153,Sunset Boulevard Luxury Private Home Escape,90028,5,9.7,9.5,10.0,10.0,9.5,9.5,9.5,...,0,0,0,0,0,0,0,0,0,(6.2 miles from center)
892,WeHo Bungalow with Private Garden,90046,16,9.7,9.7,10.0,10.0,10.0,9.1,10.0,...,0,0,0,0,0,0,0,0,0,(6.2 miles from center)

In [80]:
df_pools.loc[(df_pools['has_pool'] != 'YES' )].head(5)

,name,zip_code,number_of_reviewers,overall_score,cleanliness,comfort,facilities,staff,value_for_money,free_wifi,...,swimming_pool,very_good_fitness_center,restaurant,private_beach_area,exceptional_fitness_center,24-hour_front_desk,wifi,bbq_facilities,dist,has_pool
783,Double Suite in Santa Monica,90403,7,10.0,10.0,10.0,10.0,10.0,9.7,10.0,...,0,0,0,0,0,0,0,0,(13.7 miles from center),NO
703,Desert Heaven - Guest House,91604,173,9.8,9.9,9.9,9.8,9.9,9.7,9.9,...,0,0,0,0,0,0,0,0,(9.9 miles from center),NO
743,Tiverton Apartment Lofts,90024,5,9.8,10.0,10.0,10.0,9.5,9.0,10.0,...,0,0,0,0,0,0,0,1,(11.2 miles from center),NO
153,Sunset Boulevard Luxury Private Home Escape,90028,5,9.7,9.5,10.0,10.0,9.5,9.5,9.5,...,0,0,0,0,0,0,0,0,(6.2 miles from center),NO
892,WeHo Bungalow with Private Garden,90046,16,9.7,9.7,10.0,10.0,10.0,9.1,10.0,...,0,0,0,0,0,0,0,0,(6.2 miles from center),NO